# Generated by Django 4.0.2 on 2022-02-16 00:45

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
